# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# kubestuff
export KUBECONFIG=/etc/kubernetes/admin.conf
source <(kubectl completion bash)
PATH=$PATH:/usr/local/bin
